import os
from sqlmodel import create_engine
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    # In a real application, you might use a default SQLite database for local development
    # For this project, we require the Neon database URL.
    raise ValueError("DATABASE_URL environment variable not set. Please create a .env file with the DATABASE_URL.")

# The `echo=True` argument will print all SQL statements generated by SQLAlchemy, which is useful for debugging.
engine = create_engine(DATABASE_URL, echo=True)
